// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2f4zbKz2eTbIgGMDz8XPADMd-JXofqjc',
    appId: '1:363943754296:web:f5a3acbe3071632e6c44cd',
    messagingSenderId: '363943754296',
    projectId: 'aide-45089',
    authDomain: 'aide-45089.firebaseapp.com',
    storageBucket: 'aide-45089.firebasestorage.app',
    measurementId: 'G-7RJL51ZQXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxo5VP1egzN-jOpGpdcsQhSfSNwml8gXc',
    appId: '1:363943754296:android:1ad9ec80f5be58496c44cd',
    messagingSenderId: '363943754296',
    projectId: 'aide-45089',
    storageBucket: 'aide-45089.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo-rmQpNrsLghy7nQzfi0N4Pf1CgGzI8k',
    appId: '1:363943754296:ios:c744f68dee5c50ab6c44cd',
    messagingSenderId: '363943754296',
    projectId: 'aide-45089',
    storageBucket: 'aide-45089.firebasestorage.app',
    iosBundleId: 'com.example.aidconnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo-rmQpNrsLghy7nQzfi0N4Pf1CgGzI8k',
    appId: '1:363943754296:ios:c744f68dee5c50ab6c44cd',
    messagingSenderId: '363943754296',
    projectId: 'aide-45089',
    storageBucket: 'aide-45089.firebasestorage.app',
    iosBundleId: 'com.example.aidconnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2f4zbKz2eTbIgGMDz8XPADMd-JXofqjc',
    appId: '1:363943754296:web:7d94af896c9f0d2c6c44cd',
    messagingSenderId: '363943754296',
    projectId: 'aide-45089',
    authDomain: 'aide-45089.firebaseapp.com',
    storageBucket: 'aide-45089.firebasestorage.app',
    measurementId: 'G-JQLFS1P939',
  );
}
